### PR TITLE
Avoid removing query string after the AJAX request

### PR DESCRIPTION
**Pull request by timoffmax**

### CODE REVIEW

**Comment by ahuininga-orisha** [comment]
@timoffmax What is the bug that this fixes?

**Comment by timoffmax** [comment]
> @timoffmax What is the bug that this fixes?

Hi @ah-net,

When you go to a category and your URL contains a query string (e.g. https://myawesomesite.com/my-category?a-b&b=c) your code removes the query string because you use the URL from the AJAX response. My fix allows the original query string to stay in place.

**Comment by ahuininga-orisha** [comment]
@timoffmax 

This is done on purpose to prevent xss issues. 

In which case do you get the wrong url from the ajax response? Because the ajax response url should contain the filters/parameters that are set and used by tweakwise. If possible this should be fixed by sending the correct url in the ajax response.

**Comment by timoffmax** [comment]
@ah-net
What about other parameters some businesses may need? UTM tags, for instance? I don't see a way to catch them on the backend. Or you should send the original string in the AJAX query, process it, and return it in the response.

**Comment by ahuininga-orisha** [comment]
@timoffmax Good point, ill discuss this internally. And i will test your pull request

**Comment by timoffmax** [comment]
@ah-net 
Thanks! Feel free to adjust the code to your code style until the main purpose is still reached.

**Comment by ahuininga-orisha** [comment]
@timoffmax 

Doesn't seem to work properly. Gives an Type error on:

const responseUrl = new URL(response.url); 

The url seems correct, but the html content (the products) are not correct. Probably because of the type error. I'll see if I can find an fix for this next week.

**Comment by timoffmax** [comment]
@ah-net 
That's weird, I don't have this error, can't reproduce it. Is the response URL empty in your case?
Could you provide a URL example that causes this error?

**Comment by ahuininga-orisha** [comment]
@timoffmax It's because it's an relative url: /womens/tops-women/jackets-women/

If i add the domein name in front it seems to work.

**Comment by ahuininga-orisha** [comment]
@timoffmax I've added an change so it now works with relative url's.It now works for me. Can you check if it still works for you?

**Comment by timoffmax** [comment]
@ah-net 
I've just tested it and it still works for us. We didn't face this situation with relative URLs so that's why I missed this part.
Thanks for the fix!

**Review by ahuininga-orisha — APPROVED** [review]

**Pull request merged**
