### PR TITLE
Improve Query Param Url generation

### PR DESCRIPTION
**Pull request by igorwulff**
This PR improves performance by caching the query url and will use the cached version to build up a new url by replacing placeholder values.

### CODE REVIEW

**Comment by ahuininga-orisha** [comment]
@igorwulff I tested the performance, and the performance is actually slower. Probably because of the sha1 function. Did you test the performance? How much was the performance improvement for you?

**Comment by igorwulff** [comment]
Interesting @ah-net I tested it with larger option sets. How big were the facets for you? I tested it per "facet" by including my own profiling context in there. A sha1 call should be incredibly fast actually. I can do another profiling round and share more information.

**Comment by ahuininga-orisha** [comment]
@igorwulff My facets where not that big. Just 6 options. I'll do another test with more facets. Can you share your results?

**Comment by igorwulff** [comment]
Hi @ah-net , yes I will. Thanks also for looking into this!

**Comment by ahuininga-orisha** [comment]
I did some more tests with more facets. In some cases it is faster and in some cases a little bit slower. But the overall performance seems to be faster.

**Review by ahuininga-orisha — APPROVED** [review]

**Pull request merged**
